# local DB
DATABASE_URL=jdbc:mysql://localhost:3306/zigma
DATABASE_USERNAME=root
DATABASE_PASSWORD=333333

# jwt
JWT_SECRET_KEY = pX1oo0b9NQPoB6yRlNA6F97TSeceobmlpkswKWBTBPP2BO/qwjlD2qgCzSziEjsEX2YriO6ejz3cSm2clHqRIg==
#   30m
JWT_ACCESS_EXPIRATION = 1800000
#   14d
JWT_REFRESH_EXPIRATION = 1209600000